export const KEYWORD_CATEGORIES = {
  'Police Encounter': [
    'officer',
    'police',
    'cop',
    'cops',
    'law enforcement',
    'arrested',
    'detain',
    'detained',
    'stop and frisk',
    'search warrant',
    'search my',
    'searched me',
    'badge number',
    'excessive force',
    'police brutality',
    'handcuffed',
    'tased',
    'taser',
    'choked by',
    'qualified immunity',
    'didn\'t do anything wrong',
    'hands up',
    'on the ground',
    'stop resisting',
    'racial profiling',
    'pulled over',
    'traffic stop',
    'false arrest',
    'civil rights',
  ],

  'Workplace Concern': [
    'boss',
    'manager',
    'supervisor',
    'hr department',
    'human resources',
    'fired',
    'terminated',
    'laid off',
    'hostile work environment',
    'workplace harassment',
    'workplace discrimination',
    'quid pro quo',
    'coworker',
    'toxic workplace',
    'retaliation',
    'whistleblower',
    'passed over',
    'not promoted',
    'pay gap',
    'wage discrimination',
    'eeoc',
    'wrongful termination',
    'write up',
    'performance improvement plan',
    'pip',
  ],

  'Relationship Safety': [
    'partner',
    'boyfriend',
    'girlfriend',
    'husband',
    'wife',
    'ex',
    'ex-partner',
    'ex-boyfriend',
    'ex-girlfriend',
    'jealous',
    'controlling',
    'possessive',
    'threatened me',
    'yelled at me',
    'hit me',
    'shoved',
    'grabbed me',
    'choked me',
    'afraid of them',
    'scared of them',
    'won\'t let me leave',
    'won\'t let me see',
    'tracking my phone',
    'isolated me',
    'cut me off',
    'monitoring my',
    'reading my messages',
    'going through my phone',
    'abusive',
    'abuse',
  ],

  'Boundary / Consent Concern': [
    'i said no',
    'said no',
    'told them no',
    'no means no',
    'didn\'t consent',
    'did not consent',
    'didn\'t agree',
    'without my consent',
    'forced me',
    'forced to',
    'pressured me',
    'coerced',
    'violated',
    'sexual assault',
    'sexually assaulted',
    'touched me without',
    'unwanted touching',
    'unwanted contact',
    'groped',
    'harassed',
    'harassment',
    'he wouldn\'t stop',
    'she wouldn\'t stop',
    'they wouldn\'t stop',
    'kept pushing',
    'kept pressuring',
    'wouldn\'t take no',
  ],

  'Public Harassment': [
    'followed me',
    'following me',
    'shouted at',
    'yelled slurs',
    'racial slur',
    'slurs',
    'threatened in public',
    'confronted me',
    'surrounded',
    'street harassment',
    'public harassment',
    'being harassed',
    'approached me',
    'wouldn\'t leave me alone',
    'catcalling',
    'catcalled',
    'intimidated me',
    'intimidating',
    'made me feel unsafe',
  ],

  'Stalking / Unwanted Contact': [
    'stalking me',
    'stalked',
    'keeps showing up',
    'showing up at my',
    'won\'t stop contacting',
    'blocked them but',
    'keeps texting',
    'keeps calling',
    'leaving notes',
    'watching me',
    'being watched',
    'surveilling me',
    'surveillance',
    'following my car',
    'tracking my location',
    'spyware',
    'monitoring app',
    'parental control app',
    'won\'t leave me alone',
    'restraining order',
    'protective order',
  ],

  'Digital Safety': [
    'hacked',
    'account compromised',
    'account was hacked',
    'doxxed',
    'doxed',
    'revenge porn',
    'non-consensual images',
    'leaked my photos',
    'leaked photos',
    'spyware',
    'tracking app',
    'keylogger',
    'deepfake',
    'impersonation',
    'fake account',
    'password stolen',
    'unauthorized access',
    'two-factor disabled',
    'remote access',
    'installed something on my phone',
    'installed something on my computer',
    'online harassment',
    'cyberstalking',
    'swatting',
    'threats online',
  ],

  'Exploitation / Restricted Movement': [
    'can\'t leave',
    'won\'t let me leave',
    'locked in',
    'passport taken',
    'documents taken',
    'took my id',
    'debt bondage',
    'owes money',
    'trafficked',
    'trafficking',
    'forced to work',
    'can\'t contact family',
    'cut off from family',
    'restricted from leaving',
    'controlled my movement',
    'can\'t go anywhere',
    'forced labor',
  ],

  'Medical Concern': [
    'refused treatment',
    'denied treatment',
    'medical discrimination',
    'doctor wouldn\'t listen',
    'not believed by doctor',
    'medical neglect',
    'overdose',
    'hurt myself',
    'harmed myself',
    'self harm',
    'self-harm',
    'can\'t access care',
    'can\'t afford care',
    'medication denied',
    'misdiagnosed',
    'dismissed by doctor',
    'hospitalized',
    'mental health crisis',
    'panic attack',
    'anxiety attack',
  ],

  'Immediate Safety': [
    'i need help',
    'need help',
    'help me',
    'i\'m in danger',
    'in danger',
    'i\'m not safe',
    'not safe',
    'unsafe',
    'emergency',
    'please help',
    'call 911',
    'scared for my life',
    'fear for my life',
    'going to hurt me',
    'threatened my life',
    'death threat',
  ],
}

export function detectKeywords(text) {
  if (!text || typeof text !== 'string') {
    return { categories: [], flaggedPhrases: [] }
  }

  const lower = text.toLowerCase()
  const matchedCategories = new Set()
  const flaggedPhrases = []
  const seenPhrases = new Set()

  for (const [category, phrases] of Object.entries(KEYWORD_CATEGORIES)) {
    for (const phrase of phrases) {
      if (lower.includes(phrase) && !seenPhrases.has(phrase)) {
        seenPhrases.add(phrase)
        matchedCategories.add(category)
        flaggedPhrases.push({ phrase, category })
      }
    }
  }

  return {
    categories: Array.from(matchedCategories),
    flaggedPhrases,
  }
}
